export default {
    automaticRearrangeAfterDropNode: false,
    height: 400,
    highlightDegree: 1,
    highlightOpacity: 1,
    linkHighlightBehavior: false,
    maxZoom: 8,
    minZoom: 0.1,
    nodeHighlightBehavior: false,
    panAndZoom: false,
    staticGraph: true,
    width: 300,
    symbolMapper: {},
    colorMapper: {},
    sizeMapper: {},
    symbolKey: undefined,
    colorKey: undefined,
    sizeKey: undefined,
    node: {
        color: '#d3d3d3',
        fontColor: 'black',
        fontSize: 8,
        fontWeight: 'normal',
        highlightColor: 'SAME',
        highlightFontSize: 13,
        highlightFontWeight: 'bold',
        highlightStrokeColor: 'SAME',
        highlightStrokeWidth: 1.5,
        labelProperty: 'id',
        mouseCursor: 'pointer',
        opacity: 1.0,
        renderLabel: true,
        size: 100,
        strokeColor: 'none',
        strokeWidth: 0.1,
        svg: '',
        symbolType: 'circle'
    },
    link: {
        color: '#d3d3d3',
        opacity: 0.3,
        semanticStrokeWidth: false,
        strokeWidth: 0.5,
        highlightColor: 'lightgreen',
        opacityKey: undefined,
    }
};
